[package]
name = "pharaonik"
version = "0.1.0"
edition = "2023_10"
authors = ["Anubhav anubhav11697@gmail.com"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.18.0" }
starknet = ">=2.4.3"

[[target.starknet-contract]]
casm = true
sierra = true
allowed-libfuncs-list.name = "experimental"

[scripts]
test = "snforge test"